"""add_script_comments_final_clean

Revision ID: 8739f7e7c930
Revises: 4288f3bddcf2
Create Date: 2026-01-15 00:45:31.436286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8739f7e7c930'
down_revision: Union[str, None] = '4288f3bddcf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('script_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_script_comments_id'), ['id'], unique=False)


    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('image_urls',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_scripts_title'), ['title'], unique=False)
        batch_op.drop_column('validated')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('validated', sa.BOOLEAN(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_scripts_title'))
        batch_op.alter_column('image_urls',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('version',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)



    with op.batch_alter_table('script_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_script_comments_id'))

    op.drop_table('script_comments')
    # ### end Alembic commands ###
